In [ ]:
import numpy as np
import pandas as pd
import json
import pickle
import random

import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
import json
import pickle
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
import random

In [ ]:
# read dataframe from website
# https://data-flair.training/blogs/download-python-chatbot-data-project-source-code/

In [ ]:
from google.colab import files
files.upload() # Select your intents.json file here

Saving intents.json to intents (2).json


{'intents (2).json': b'{"intents": [\n        {"tag": "greeting",\n         "patterns": ["Hi there", "How are you", "Is anyone there?","Hey","Hola", "Hello", "Good day"],\n         "responses": ["Hello, thanks for asking", "Good to see you again", "Hi there, how can I help?"],\n         "context": [""]\n        },\n        {"tag": "goodbye",\n         "patterns": ["Bye", "See you later", "Goodbye", "Nice chatting to you, bye", "Till next time"],\n         "responses": ["See you!", "Have a nice day", "Bye! Come back again soon."],\n         "context": [""]\n        },\n        {"tag": "thanks",\n         "patterns": ["Thanks", "Thank you", "That\'s helpful", "Awesome, thanks", "Thanks for helping me"],\n         "responses": ["Happy to help!", "Any time!", "My pleasure"],\n         "context": [""]\n        },\n        {"tag": "noanswer",\n         "patterns": [],\n         "responses": ["Sorry, can\'t understand you", "Please give me more info", "Not sure I understand"],\n         "cont

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

import json
import pickle
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
import random

"""
# Load data from intents.json

data_file = open('intents.json').read()

intents = json.loads(data_file)"""

"\n# Load data from intents.json\n\ndata_file = open('intents.json').read()\n\nintents = json.loads(data_file)"

In [ ]:
!pip install chatterbot

!pip install chatterbot_corpus

In [ ]:
import json

with open('intents.json') as file:
    data = json.load(file)

for intent in data['intents']:
    print(f"Tag: {intent['tag']}")
    print(f"Patterns: {intent['patterns']}")
    print(f"Responses: {intent['responses']}")
    print("-" * 20)


Tag: greeting
Patterns: ['Hi there', 'How are you', 'Is anyone there?', 'Hey', 'Hola', 'Hello', 'Good day']
Responses: ['Hello, thanks for asking', 'Good to see you again', 'Hi there, how can I help?']
--------------------
Tag: goodbye
Patterns: ['Bye', 'See you later', 'Goodbye', 'Nice chatting to you, bye', 'Till next time']
Responses: ['See you!', 'Have a nice day', 'Bye! Come back again soon.']
--------------------
Tag: thanks
Patterns: ['Thanks', 'Thank you', "That's helpful", 'Awesome, thanks', 'Thanks for helping me']
Responses: ['Happy to help!', 'Any time!', 'My pleasure']
--------------------
Tag: noanswer
Patterns: []
Responses: ["Sorry, can't understand you", 'Please give me more info', 'Not sure I understand']
--------------------
Tag: options
Patterns: ['How you could help me?', 'What you can do?', 'What help you provide?', 'How you can be helpful?', 'What support is offered']
Responses: ['I can guide you through Adverse drug reaction list, Blood pressure tracking, Hospit

In [ ]:
import pandas as pd

rows = []

for intent in data['intents']:
    for pattern in intent['patterns']:
        rows.append({
            'tag': intent['tag'],
            'pattern': pattern,
            'responses': intent['responses']
        })

df = pd.DataFrame(rows)

print(df.head())

        tag           pattern  \
0  greeting          Hi there   
1  greeting       How are you   
2  greeting  Is anyone there?   
3  greeting               Hey   
4  greeting              Hola   

                                           responses  
0  [Hello, thanks for asking, Good to see you aga...  
1  [Hello, thanks for asking, Good to see you aga...  
2  [Hello, thanks for asking, Good to see you aga...  
3  [Hello, thanks for asking, Good to see you aga...  
4  [Hello, thanks for asking, Good to see you aga...  


In [ ]:
df

tag                                            pattern  \
0                greeting                                           Hi there   
1                greeting                                        How are you   
2                greeting                                   Is anyone there?   
3                greeting                                                Hey   
4                greeting                                               Hola   
5                greeting                                              Hello   
6                greeting                                           Good day   
7                 goodbye                                                Bye   
8                 goodbye                                      See you later   
9                 goodbye                                            Goodbye   
10                goodbye                          Nice chatting to you, bye   
11                goodbye                                     Till next time   
12                 thanks                                             Thanks   
13                 thanks                                          Thank you   
14                 thanks                                     That's helpful   
15                 thanks                                    Awesome, thanks   
16                 thanks                              Thanks for helping me   
17                options                             How you could help me?   
18                options                                   What you can do?   
19                options                             What help you provide?   
20                options                            How you can be helpful?   
21                options                            What support is offered   
22           adverse_drug                How to check Adverse drug reaction?   
23           adverse_drug                          Open adverse drugs module   
24           adverse_drug   Give me a list of drugs causing adverse behavior   
25           adverse_drug  List all drugs suitable for patient with adver...   
26           adverse_drug            Which drugs dont have adverse reaction?   
27         blood_pressure                         Open blood pressure module   
28         blood_pressure                     Task related to blood pressure   
29         blood_pressure                          Blood pressure data entry   
30         blood_pressure               I want to log blood pressure results   
31         blood_pressure                     Blood pressure data management   
32  blood_pressure_search  I want to search for blood pressure result his...   
33  blood_pressure_search                         Blood pressure for patient   
34  blood_pressure_search                 Load patient blood pressure result   
35  blood_pressure_search            Show blood pressure results for patient   
36  blood_pressure_search                  Find blood pressure results by ID   
37        pharmacy_search                                 Find me a pharmacy   
38        pharmacy_search                                      Find pharmacy   
39        pharmacy_search                          List of pharmacies nearby   
40        pharmacy_search                                    Locate pharmacy   
41        pharmacy_search                                    Search pharmacy   
42        hospital_search                                Lookup for hospital   
43        hospital_search         Searching for hospital to transfer patient   
44        hospital_search                     I want to search hospital data   
45        hospital_search                        Hospital lookup for patient   
46        hospital_search                        Looking up hospital details   

                                            responses  
0   [Hello, thanks for asking, Good to see you aga...  
1   [Hello, thanks for asking, Good to see you aga...  
2   [Hello, t

In [ ]:
df['tag'].unique()

array(['greeting', 'goodbye', 'thanks', 'options', 'adverse_drug',
       'blood_pressure', 'blood_pressure_search', 'pharmacy_search',
       'hospital_search'], dtype=object)

In [ ]:
df['pattern'].unique()

array(['Hi there', 'How are you', 'Is anyone there?', 'Hey', 'Hola',
       'Hello', 'Good day', 'Bye', 'See you later', 'Goodbye',
       'Nice chatting to you, bye', 'Till next time', 'Thanks',
       'Thank you', "That's helpful", 'Awesome, thanks',
       'Thanks for helping me', 'How you could help me?',
       'What you can do?', 'What help you provide?',
       'How you can be helpful?', 'What support is offered',
       'How to check Adverse drug reaction?', 'Open adverse drugs module',
       'Give me a list of drugs causing adverse behavior',
       'List all drugs suitable for patient with adverse reaction',
       'Which drugs dont have adverse reaction?',
       'Open blood pressure module', 'Task related to blood pressure',
       'Blood pressure data entry',
       'I want to log blood pressure results',
       'Blood pressure data management',
       'I want to search for blood pressure result history',
       'Blood pressure for patient', 'Load patient blood pressure r

In [ ]:
df_grouped = df.groupby('tag')['responses'].first().reset_index()
print(df_grouped)

                     tag                                          responses
0           adverse_drug       [Navigating to Adverse drug reaction module]
1         blood_pressure              [Navigating to Blood Pressure module]
2  blood_pressure_search           [Please provide Patient ID, Patient ID?]
3                goodbye  [See you!, Have a nice day, Bye! Come back aga...
4               greeting  [Hello, thanks for asking, Good to see you aga...
5        hospital_search         [Please provide hospital name or location]
6                options  [I can guide you through Adverse drug reaction...
7        pharmacy_search                     [Please provide pharmacy name]
8                 thanks           [Happy to help!, Any time!, My pleasure]


In [ ]:
#(NLTK), SpaCy, and TextBlob when building a chatbot

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

tokenized_data = []
for sentence in df:
    tokens = nltk.word_tokenize(sentence.lower())
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    filtered_tokens = [token for token in lemmatized_tokens if token not in stop_words]
    tokenized_data.append(filtered_tokens)

for i in range(len(tokenized_data)):
    tokenized_data[i] = list(set(tokenized_data[i]))

print(tokenized_data)

[['tag'], ['pattern'], ['response']]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
words=[]
classes = []
documents = []
ignore_words = ['?', '!']
data_file = open('intents.json').read()
intents = json.loads(data_file)

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
for intent in intents['intents']:
    for pattern in intent['patterns']:
        w = nltk.word_tokenize(pattern)
        words.extend(w)

        documents.append((w, intent['tag']))
        if intent['tag'] not in classes:
            classes.append(intent['tag'])

In [ ]:

words = [lemmatizer.lemmatize(w.lower()) for w in words if w not in ignore_words]
words = sorted(list(set(words)))

classes = sorted(list(set(classes)))

print (len(documents), "documents")

print (len(classes), "classes", classes)

print (len(words), "unique lemmatized words", words)
pickle.dump(words,open('words.pkl','wb'))
pickle.dump(classes,open('classes.pkl','wb'))

47 documents
9 classes ['adverse_drug', 'blood_pressure', 'blood_pressure_search', 'goodbye', 'greeting', 'hospital_search', 'options', 'pharmacy_search', 'thanks']
88 unique lemmatized words ["'s", ',', 'a', 'adverse', 'all', 'anyone', 'are', 'awesome', 'be', 'behavior', 'blood', 'by', 'bye', 'can', 'causing', 'chatting', 'check', 'could', 'data', 'day', 'detail', 'do', 'dont', 'drug', 'entry', 'find', 'for', 'give', 'good', 'goodbye', 'have', 'hello', 'help', 'helpful', 'helping', 'hey', 'hi', 'history', 'hola', 'hospital', 'how', 'i', 'id', 'is', 'later', 'list', 'load', 'locate', 'log', 'looking', 'lookup', 'management', 'me', 'module', 'nearby', 'next', 'nice', 'of', 'offered', 'open', 'patient', 'pharmacy', 'pressure', 'provide', 'reaction', 'related', 'result', 'search', 'searching', 'see', 'show', 'suitable', 'support', 'task', 'thank', 'thanks', 'that', 'there', 'till', 'time', 'to', 'transfer', 'up', 'want', 'what', 'which', 'with', 'you']


In [ ]:
df

tag                                            pattern  \
0                greeting                                           Hi there   
1                greeting                                        How are you   
2                greeting                                   Is anyone there?   
3                greeting                                                Hey   
4                greeting                                               Hola   
5                greeting                                              Hello   
6                greeting                                           Good day   
7                 goodbye                                                Bye   
8                 goodbye                                      See you later   
9                 goodbye                                            Goodbye   
10                goodbye                          Nice chatting to you, bye   
11                goodbye                                     Till next time   
12                 thanks                                             Thanks   
13                 thanks                                          Thank you   
14                 thanks                                     That's helpful   
15                 thanks                                    Awesome, thanks   
16                 thanks                              Thanks for helping me   
17                options                             How you could help me?   
18                options                                   What you can do?   
19                options                             What help you provide?   
20                options                            How you can be helpful?   
21                options                            What support is offered   
22           adverse_drug                How to check Adverse drug reaction?   
23           adverse_drug                          Open adverse drugs module   
24           adverse_drug   Give me a list of drugs causing adverse behavior   
25           adverse_drug  List all drugs suitable for patient with adver...   
26           adverse_drug            Which drugs dont have adverse reaction?   
27         blood_pressure                         Open blood pressure module   
28         blood_pressure                     Task related to blood pressure   
29         blood_pressure                          Blood pressure data entry   
30         blood_pressure               I want to log blood pressure results   
31         blood_pressure                     Blood pressure data management   
32  blood_pressure_search  I want to search for blood pressure result his...   
33  blood_pressure_search                         Blood pressure for patient   
34  blood_pressure_search                 Load patient blood pressure result   
35  blood_pressure_search            Show blood pressure results for patient   
36  blood_pressure_search                  Find blood pressure results by ID   
37        pharmacy_search                                 Find me a pharmacy   
38        pharmacy_search                                      Find pharmacy   
39        pharmacy_search                          List of pharmacies nearby   
40        pharmacy_search                                    Locate pharmacy   
41        pharmacy_search                                    Search pharmacy   
42        hospital_search                                Lookup for hospital   
43        hospital_search         Searching for hospital to transfer patient   
44        hospital_search                     I want to search hospital data   
45        hospital_search                        Hospital lookup for patient   
46        hospital_search                        Looking up hospital details   

                                            responses  
0   [Hello, thanks for asking, Good to see you aga...  
1   [Hello, thanks for asking, Good to see you aga...  
2   [Hello, t

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
import numpy as np

lemmatizer = WordNetLemmatizer()

def bow(sentence, words, show_details=True):
    sentence_words = nltk.word_tokenize(sentence)
    sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]

    bag = [0] * len(words)
    for s in sentence_words:
        for i, w in enumerate(words):
            if w == s:
                bag[i] = 1
                if show_details:
                    print(f"found in bag: {w}")

    return np.array(bag)

def predict_class(sentence, model):
    p = bow(sentence, words, show_details=False)

    res = model.predict(np.array([p]), verbose=0)[0]
    ERROR_THRESHOLD = 0.25
    results = [[i, r] for i, r in enumerate(res) if r > ERROR_THRESHOLD]

    results.sort(key=lambda x: x[1], reverse=True)

    return_list = []
    for r in results:
        return_list.append({
            "intent": classes[r[0]],
            "probability": str(r[1])
        })

    return return_list

df['responses_text'] = df['responses'].apply(
    lambda x: ' '.join(x) if isinstance(x, list) else str(x)
)

# Now apply predictions
df['predictions'] = df['responses_text'].apply(lambda x: predict_class(x, model))
df['predicted_intent'] = df['responses_text'].apply(
    lambda x: predict_class(x, model)[0]['intent'] if predict_class(x, model) else None
)
df['confidence'] = df['responses_text'].apply(
    lambda x: predict_class(x, model)[0]['probability'] if predict_class(x, model) else None
)

In [ ]:
# 1. SPLIT YOUR DATA
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(documents, test_size=0.2, random_state=42)

# 2. PREPARE TRAINING DATA
def prepare_data(data_docs, words, classes):
    training = []
    output_empty = [0] * len(classes)

    for doc in data_docs:
        bag = []
        pattern_words = doc[0]
        pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]

        for w in words:
            bag.append(1) if w in pattern_words else bag.append(0)

        output_row = list(output_empty)
        output_row[classes.index(doc[1])] = 1
        training.append([bag, output_row])

    random.shuffle(training)

    train_x = []
    train_y = []
    for item in training:
        train_x.append(item[0])
        train_y.append(item[1])

    return np.array(train_x), np.array(train_y)

train_x, train_y = prepare_data(train_data, words, classes)
test_x, test_y = prepare_data(test_data, words, classes)

In [ ]:
# 3. BUILD MODEL
model = Sequential()
model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(train_y[0]), activation='softmax'))

# 4. COMPILE MODEL
sgd = SGD(learning_rate=0.01, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# 5. TRAIN MODEL
history = model.fit(train_x, train_y,
                    epochs=200,
                    batch_size=5,
                    verbose=1,
                    validation_data=(test_x, test_y))  # Add validation data

# 6. EVALUATE ON TEST SET
test_loss, test_accuracy = model.evaluate(test_x, test_y, verbose=0)
print(f"\nTest Accuracy: {test_accuracy*100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# 7. GET PREDICTIONS ON TEST SET
predictions = model.predict(test_x)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(test_y, axis=1)

Epoch 1/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.0592 - loss: 2.3095 - val_accuracy: 0.0000e+00 - val_loss: 2.2794
Epoch 2/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2440 - loss: 2.2118 - val_accuracy: 0.1000 - val_loss: 2.2488
Epoch 3/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1488 - loss: 2.1898 - val_accuracy: 0.2000 - val_loss: 2.2262
Epoch 4/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3540 - loss: 2.1069 - val_accuracy: 0.3000 - val_loss: 2.2186
Epoch 5/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1832 - loss: 2.0819 - val_accuracy: 0.3000 - val_loss: 2.2129
Epoch 6/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3543 - loss: 1.9323 - val_accuracy: 0.3000 - val_loss: 2.2008
Epoch 7/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3641 - loss: 1.8623 - val_accuracy: 0.3000 - val_loss: 2.1604
Epoch 8/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3969 - loss: 1.7766 - val_accuracy: 0.3000 - val_l

In [ ]:
predictions = model.predict(test_x, verbose=0)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(test_y, axis=1)

# 8. DETAILED EVALUATION
print("\nClassification Report:")
try:
    print(classification_report(true_classes, predicted_classes, target_names=classes))
except ValueError as e:
    print(f"Error in classification report: {e}")
    print(classification_report(true_classes, predicted_classes))

print("\nConfusion Matrix:")
print(confusion_matrix(true_classes, predicted_classes))

accuracy = accuracy_score(true_classes, predicted_classes)
print(f"\nTest Accuracy: {accuracy*100:.2f}%")

# 9. SAVE MODEL AND DATA
model.save('chatbot_model.h5')
pickle.dump(words, open('words.pkl', 'wb'))
pickle.dump(classes, open('classes.pkl', 'wb'))

print("\nModel saved successfully!")


Classification Report:
Error in classification report: Number of classes, 8, does not match size of target_names, 9. Try specifying the labels parameter
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         1

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10


Confusion Matrix:
[[3 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]

Test Accuracy: 100.00%

In [ ]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(documents, test_size=0.2, random_state=42)

def prepare_data(data_docs, words, classes):
    training = []
    output_empty = [0] * len(classes)

    for doc in data_docs:
        bag = []
        pattern_words = doc[0]
        pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]

        for w in words:
            bag.append(1) if w in pattern_words else bag.append(0)

        output_row = list(output_empty)
        output_row[classes.index(doc[1])] = 1
        training.append([bag, output_row])

    x = []
    y = []
    for item in training:
        x.append(item[0])
        y.append(item[1])

    return np.array(x), np.array(y)

test_x, test_y = prepare_data(test_data, words, classes)

In [ ]:
def chat():
    while True:
        user_input = input("\nYou: ")

        if user_input.lower() in ['quit', 'exit', 'bye']:
            print("Chatbot: Goodbye!")
            break

        predictions = predict_class(user_input, model)

        if predictions:
            intent = predictions[0]['intent']
            confidence = float(predictions[0]['probability'])

            print(f"Bot: Intent detected - '{intent}' (confidence: {confidence*100:.2f}%)")
        else:
            print("Bot: I'm not sure what you mean (confidence too low)")

chat()

Chatbot is ready! Type 'quit' to exit.
--------------------------------------------------

You: hi
Bot: Intent detected - 'greeting' (confidence: 98.91%)

You: how are you?
Bot: Intent detected - 'greeting' (confidence: 99.99%)

You: can you give me a details about you?
Bot: Intent detected - 'options' (confidence: 99.87%)

You: bye
Chatbot: Goodbye!
